### ISSUE TITLE
Research kinds of messages allowed to be sent.

### ISSUE THREAD

**Issue by BigPapaChas** [BigPapaChas/ow-bot#4]

**Comment by chrislockard21** [comment]
The structure of a discord message that can be sent with the Webhook can be found here: https://discord.com/developers/docs/resources/webhook#execute-webhook. It is fairly limited so we will probably need to send multiple messages depending on what the user is looking to receive. We will need to use images of graphs and individual messages to present the data.

**Comment by BigPapaChas** [comment]
@chrislockard21 Can you add a wiki page that provides a summary of what can be gleaned from that link? Additionally on that wiki page, could you go into more detail as to what some of our options would be with this approach? Then we can close this story and open a new one where we can actually test some of these different options. The new story would include attaching images to what each of the different options would look like and we can decide as a team what looks best.

**Comment by chrislockard21** [comment]
Added a wiki page for the structure of discord messages [https://github.com/BigPapaChas/ow-bot/wiki/Discord-Message-Structure](url)
